#Library

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
!pip install kaggle
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [ ]:
!kaggle datasets download -d muhtarom/stunting-dataset

  0% 0.00/44.4k [00:00<?, ?B/s]
100% 44.4k/44.4k [00:00<00:00, 48.6MB/s]


In [ ]:
!unzip stunting-dataset.zip -d './data'

Archive:  stunting-dataset.zip
  inflating: ./data/Stunting_Dataset.csv  


#Load Data

In [ ]:
data = pd.read_csv('/content/data/Stunting_Dataset.csv')
data

Gender  Age  Birth Weight  Birth Length  Body Weight  Body Length  \
0       Male   17           3.0            49         10.0         72.2   
1     Female   11           2.9            49          2.9         65.0   
2       Male   16           2.9            49          8.5         72.2   
3       Male   31           2.8            49          6.4         63.0   
4       Male   15           3.1            49         10.5         49.0   
...      ...  ...           ...           ...          ...          ...   
9995    Male   15           3.0            49          9.0         63.0   
9996  Female   12           2.8            48          7.7         63.0   
9997    Male   16           2.8            49          7.7         49.0   
9998    Male   14           2.8            49         10.0         69.0   
9999  Female   10           3.0            49          7.7         80.0   

     Breastfeeding Stunting  
0               No       No  
1               No      Yes  
2               No      Yes  
3               No      Yes  
4               No      Yes  
...            ...      ...  
9995            No      Yes  
9996            No       No  
9997            No       No  
9998            No      Yes  
9999            No      Yes  

[10000 rows x 8 columns]

import numpy as np
from google.colab import autoviz
df_613629012636792366 = autoviz.get_df('df_613629012636792366')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_613629012636792366, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz
df_3567151567156355367 = autoviz.get_df('df_3567151567156355367')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_3567151567156355367, *['Birth Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1660453853318247023 = autoviz.get_df('df_1660453853318247023')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_1660453853318247023, *['Birth Length'], **{})
chart

import numpy as np
from google.colab import autoviz
df_4693136149648269414 = autoviz.get_df('df_4693136149648269414')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_4693136149648269414, *['Body Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_4068343772269292530 = autoviz.get_df('df_4068343772269292530')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_4068343772269292530, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz
df_5476242125350278771 = autoviz.get_df('df_5476242125350278771')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_5476242125350278771, *['Birth Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_7997731247388066967 = autoviz.get_df('df_7997731247388066967')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_7997731247388066967, *['Birth Length'], **{})
chart

import numpy as np
from google.colab import autoviz
df_7503202165816458622 = autoviz.get_df('df_7503202165816458622')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_7503202165816458622, *['Body Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2463018563518572577 = autoviz.get_df('df_2463018563518572577')

def categorical_histogram(df, colname, figsize=(2, 1.2), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  _, ax = plt.subplots(figsize=figsize)
  bars = df[colname].value_counts()
  plt.barh(bars.index, bars.values, color=sns.palettes.mpl_palette(mpl_palette_name))
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df_2463018563518572577, *['Gender'], **{})
chart

import numpy as np
from google.colab import autoviz
df_1282444928634338959 = autoviz.get_df('df_1282444928634338959')

def categorical_histogram(df, colname, figsize=(2, 1.2), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  _, ax = plt.subplots(figsize=figsize)
  bars = df[colname].value_counts()
  plt.barh(bars.index, bars.values, color=sns.palettes.mpl_palette(mpl_palette_name))
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df_1282444928634338959, *['Stunting'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2853172229847192540 = autoviz.get_df('df_2853172229847192540')

def scatter_plots(df, colname_pairs, scatter_plot_size=2.5, size=8, alpha=.6):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * scatter_plot_size, scatter_plot_size))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    ax.scatter(df[x_colname], df[y_colname], s=size, alpha=alpha)
    plt.xlabel(x_colname)
    plt.ylabel(y_colname)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df_2853172229847192540, *[[['Age', 'Birth Weight'], ['Birth Weight', 'Birth Length'], ['Birth Length', 'Body Weight'], ['Body Weight', 'Body Length']]], **{})
chart

import numpy as np
from google.colab import autoviz
df_2687288192298476481 = autoviz.get_df('df_2687288192298476481')

def heatmap(df, x_colname, y_colname, figsize=(2, 2), mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=figsize)
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(df_2687288192298476481, *['Gender', 'Stunting'], **{})
chart

import numpy as np
from google.colab import autoviz
df_3633054228357165268 = autoviz.get_df('df_3633054228357165268')

def violin_plot(df, value_colname, facet_colname, col_width=.3, col_length=3, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  plt.figure(figsize=(col_length, col_width * len(df[facet_colname].unique())))
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df_3633054228357165268, *['Age', 'Gender'], **{'inner': 'box'})
chart

import numpy as np
from google.colab import autoviz
df_9004441008963804916 = autoviz.get_df('df_9004441008963804916')

def violin_plot(df, value_colname, facet_colname, col_width=.3, col_length=3, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  plt.figure(figsize=(col_length, col_width * len(df[facet_colname].unique())))
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df_9004441008963804916, *['Age', 'Stunting'], **{'inner': 'box'})
chart

import numpy as np
from google.colab import autoviz
df_7942973205204161292 = autoviz.get_df('df_7942973205204161292')

def violin_plot(df, value_colname, facet_colname, col_width=.3, col_length=3, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  plt.figure(figsize=(col_length, col_width * len(df[facet_colname].unique())))
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df_7942973205204161292, *['Birth Weight', 'Gender'], **{'inner': 'box'})
chart

import numpy as np
from google.colab import autoviz
df_8871307980524413681 = autoviz.get_df('df_8871307980524413681')

def violin_plot(df, value_colname, facet_colname, col_width=.3, col_length=3, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  plt.figure(figsize=(col_length, col_width * len(df[facet_colname].unique())))
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df_8871307980524413681, *['Birth Weight', 'Stunting'], **{'inner': 'box'})
chart

#Data Understanding

In [ ]:
data.head()

Gender  Age  Birth Weight  Birth Length  Body Weight  Body Length  \
0    Male   17           3.0            49         10.0         72.2   
1  Female   11           2.9            49          2.9         65.0   
2    Male   16           2.9            49          8.5         72.2   
3    Male   31           2.8            49          6.4         63.0   
4    Male   15           3.1            49         10.5         49.0   

  Breastfeeding Stunting  
0            No       No  
1            No      Yes  
2            No      Yes  
3            No      Yes  
4            No      Yes

In [ ]:
data.columns.tolist()

['Gender',
 'Age',
 'Birth Weight',
 'Birth Length',
 'Body Weight',
 'Body Length',
 'Breastfeeding',
 'Stunting']

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Gender         10000 non-null  object 
 1   Age            10000 non-null  int64  
 2   Birth Weight   10000 non-null  float64
 3   Birth Length   10000 non-null  int64  
 4   Body Weight    10000 non-null  float64
 5   Body Length    10000 non-null  float64
 6   Breastfeeding  10000 non-null  object 
 7   Stunting       10000 non-null  object 
dtypes: float64(3), int64(2), object(3)
memory usage: 625.1+ KB


In [ ]:
data.corr()

<ipython-input-14-c44ded798807>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()


Age  Birth Weight  Birth Length  Body Weight  Body Length
Age           1.000000      0.079891     -0.121064     0.065459     0.045597
Birth Weight  0.079891      1.000000     -0.184841     0.063805     0.019343
Birth Length -0.121064     -0.184841      1.000000    -0.077445    -0.026012
Body Weight   0.065459      0.063805     -0.077445     1.000000    -0.006291
Body Length   0.045597      0.019343     -0.026012    -0.006291     1.000000

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_2355394893938669394, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_2355394893938669394, *['Birth Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_2355394893938669394, *['Birth Length'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_2355394893938669394, *['Body Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_2355394893938669394, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_2355394893938669394, *['Birth Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_2355394893938669394, *['Birth Length'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_2355394893938669394, *['Body Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_2355394893938669394 = autoviz.get_df('df_2355394893938669394')

def scatter_plots(df, colname_pairs, scatter_plot_size=2.5, size=8, alpha=.6):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * scatter_plot_size, scatter_plot_size))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    ax.scatter(df[x_colname], df[y_colname], s=size, alpha=alpha)
    plt.xlabel(x_colname)
    plt.ylabel(y_colname)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df_2355394893938669394, *[[['Age', 'Birth Weight'], ['Birth Weight', 'Birth Length'], ['Birth Length', 'Body Weight'], ['Body Weight', 'Body Length']]], **{})
chart

In [ ]:
data.describe()

Age  Birth Weight  Birth Length   Body Weight  Body Length
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.00000
mean      14.255000      2.757600     49.117400      7.631990     68.85492
std        7.923285      0.291092      0.439814      1.720461      8.90664
min        6.000000      2.000000     48.000000      2.900000     49.00000
25%       10.000000      2.800000     49.000000      6.400000     65.00000
50%       13.000000      2.800000     49.000000      7.700000     68.30000
75%       15.000000      2.900000     49.000000      9.000000     72.20000
max       48.000000      3.100000     50.000000     10.500000     92.70000

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8621490442566089387, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8621490442566089387, *['Birth Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8621490442566089387, *['Birth Length'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8621490442566089387, *['Body Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8621490442566089387, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8621490442566089387, *['Birth Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8621490442566089387, *['Birth Length'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8621490442566089387, *['Body Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8621490442566089387 = autoviz.get_df('df_8621490442566089387')

def scatter_plots(df, colname_pairs, scatter_plot_size=2.5, size=8, alpha=.6):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * scatter_plot_size, scatter_plot_size))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    ax.scatter(df[x_colname], df[y_colname], s=size, alpha=alpha)
    plt.xlabel(x_colname)
    plt.ylabel(y_colname)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df_8621490442566089387, *[[['Age', 'Birth Weight'], ['Birth Weight', 'Birth Length'], ['Birth Length', 'Body Weight'], ['Body Weight', 'Body Length']]], **{})
chart

In [ ]:
data.shape

(10000, 8)

In [ ]:
data.dtypes

Gender            object
Age                int64
Birth Weight     float64
Birth Length       int64
Body Weight      float64
Body Length      float64
Breastfeeding     object
Stunting          object
dtype: object

#EDA

In [ ]:
#Missing value
data.isna().sum()

Gender           0
Age              0
Birth Weight     0
Birth Length     0
Body Weight      0
Body Length      0
Breastfeeding    0
Stunting         0
dtype: int64

In [ ]:
data[data.Stunting=='?'] #Gender, Breastfeeding, Stunting aman

Empty DataFrame
Columns: [Gender, Age, Birth Weight, Birth Length, Body Weight, Body Length, Breastfeeding, Stunting]
Index: []

No charts were generated by quickchart


In [ ]:
#encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for column in data.columns:
  if data[column].dtype == 'object':
    data[column + '-Encoded'] = le.fit_transform(data[column])

#Delete data kategori
data_encoded = data.drop(columns=data.select_dtypes(include='object').columns)
print(data_encoded)

      Age  Birth Weight  Birth Length  Body Weight  Body Length  \
0      17           3.0            49         10.0         72.2   
1      11           2.9            49          2.9         65.0   
2      16           2.9            49          8.5         72.2   
3      31           2.8            49          6.4         63.0   
4      15           3.1            49         10.5         49.0   
...   ...           ...           ...          ...          ...   
9995   15           3.0            49          9.0         63.0   
9996   12           2.8            48          7.7         63.0   
9997   16           2.8            49          7.7         49.0   
9998   14           2.8            49         10.0         69.0   
9999   10           3.0            49          7.7         80.0   

      Gender-Encoded  Breastfeeding-Encoded  Stunting-Encoded  
0                  1                      0                 0  
1                  0                      0                 1  
2  

Hasil Encoding

Male -> 1

Female -> 0

No -> 0

Yes -> 1

In [ ]:
#dependent & Independent
X = data_encoded.iloc[:, :-1].values
y = data_encoded.iloc[:, -1]

In [ ]:
X

array([[17. ,  3. , 49. , ..., 72.2,  1. ,  0. ],
       [11. ,  2.9, 49. , ..., 65. ,  0. ,  0. ],
       [16. ,  2.9, 49. , ..., 72.2,  1. ,  0. ],
       ...,
       [16. ,  2.8, 49. , ..., 49. ,  1. ,  0. ],
       [14. ,  2.8, 49. , ..., 69. ,  1. ,  0. ],
       [10. ,  3. , 49. , ..., 80. ,  0. ,  0. ]])

In [ ]:
y

0       0
1       1
2       1
3       1
4       1
       ..
9995    1
9996    0
9997    0
9998    1
9999    1
Name: Stunting-Encoded, Length: 10000, dtype: int64

In [ ]:
#Normalize
from sklearn.preprocessing import Normalizer
transform = Normalizer().fit(X)
transform

Normalizer()

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
scaler.transform(X)

array([[ 0.34646451,  0.83276727, -0.26694421, ...,  0.37559028,
         0.78221692,  0.        ],
       [-0.41083497,  0.48921642, -0.26694421, ..., -0.43283583,
        -1.27841775,  0.        ],
       [ 0.22024793,  0.48921642, -0.26694421, ...,  0.37559028,
         0.78221692,  0.        ],
       ...,
       [ 0.22024793,  0.14566556, -0.26694421, ..., -2.22933831,
         0.78221692,  0.        ],
       [-0.03218523,  0.14566556, -0.26694421, ...,  0.01628979,
         0.78221692,  0.        ],
       [-0.53705155,  0.83276727, -0.26694421, ...,  1.25138524,
        -1.27841775,  0.        ]])

In [ ]:
#Optimization using PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [ ]:
#Split 70 30
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
# #Undersampling
# from imblearn.under_sampling import RandomUnderSampler
# rus = RandomUnderSampler(random_state=42)
# rus.fit_resample(X_train, y_train)

(array([[12. ,  2.8, 49. , ..., 63. ,  1. ,  0. ],
        [17. ,  2.9, 49. , ..., 73.5,  1. ,  0. ],
        [10. ,  2.3, 50. , ..., 65. ,  0. ,  0. ],
        ...,
        [ 7. ,  2.8, 49. , ..., 49. ,  0. ,  0. ],
        [12. ,  3. , 49. , ..., 72.2,  0. ,  0. ],
        [15. ,  3. , 49. , ..., 71. ,  0. ,  0. ]]),
 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 2873    1
 2874    1
 2875    1
 2876    1
 2877    1
 Name: Stunting-Encoded, Length: 2878, dtype: int64)

In [ ]:
#Oversampling
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
smote.fit_resample(X_train, y_train)

(array([[10.        ,  2.8       , 49.        , ..., 68.3       ,
          1.        ,  0.        ],
        [12.        ,  2.8       , 49.        , ..., 63.        ,
          1.        ,  0.        ],
        [15.        ,  3.1       , 49.        , ..., 76.        ,
          1.        ,  0.        ],
        ...,
        [17.        ,  2.86852015, 49.        , ..., 65.        ,
          0.31479855,  0.        ],
        [ 6.        ,  2.3       , 50.        , ..., 68.3       ,
          1.        ,  0.        ],
        [ 9.61778826,  2.8       , 50.        , ..., 49.        ,
          1.        ,  0.        ]]),
 0        1
 1        0
 2        1
 3        1
 4        0
         ..
 11117    0
 11118    0
 11119    0
 11120    0
 11121    0
 Name: Stunting-Encoded, Length: 11122, dtype: int64)

#Model

Random Forest

In [ ]:
#Model Random Forest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(max_depth=5, random_state=0)
RF.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=0)

In [ ]:
#Predict Random Forest
pred_RF = RF.predict(X_test)
pred_RF

array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
#Evaluation Random Forest
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
cf_RF = classification_report(y_test, pred_RF, labels=[0, 1])
acc_RF = accuracy_score(y_test, pred_RF)
print(cf_RF)
print('Accuracy : ', acc_RF)

              precision    recall  f1-score   support

           0       0.79      0.40      0.53       606
           1       0.87      0.97      0.92      2394

    accuracy                           0.86      3000
   macro avg       0.83      0.69      0.72      3000
weighted avg       0.85      0.86      0.84      3000

Accuracy :  0.857


In [ ]:
#Confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm_RF = confusion_matrix(y_test, pred_RF)
print(cm_RF)

[[ 243  363]
 [  66 2328]]


Logistic Regression

In [ ]:
#Model
from sklearn.linear_model import LogisticRegression
Logreg = LogisticRegression(random_state = 0)
Logreg.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
#Predict Logistic Regression
pred_Logreg = Logreg.predict(X_test)
pred_Logreg

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
#Evaluation
cf_LR = classification_report(y_test, pred_Logreg, labels=[0, 1])
acc_LR = accuracy_score(y_test, pred_Logreg)
print(cf_LR)
print('Accuracy : ', acc_LR)

              precision    recall  f1-score   support

           0       0.72      0.37      0.49       606
           1       0.86      0.96      0.91      2394

    accuracy                           0.84      3000
   macro avg       0.79      0.67      0.70      3000
weighted avg       0.83      0.84      0.82      3000

Accuracy :  0.844


In [ ]:
#Confusion matrix
cm_LR = confusion_matrix(y_test, pred_Logreg)
print(cm_LR)

[[ 225  381]
 [  87 2307]]


Check

In [ ]:
check = pd.DataFrame({'X1' : [1],
                      'X2' : [10],
                      'X3': [2.3],
                      'X4': [30],
                      'X5' : [6.5],
                      'X6' : [55.5],
                      'X7' : [0]})
prediction = RF.predict(check)
print('Hasil Pred :', prediction)

Hasil Pred : [1]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


Hasil predict pada variable check termasuk stunting. Menggunakan Random Forest

In [ ]:
check2 = pd.DataFrame({'X1' : [1],
                      'X2' : [10],
                      'X3': [2.3],
                      'X4': [30],
                      'X5' : [6.5],
                      'X6' : [55.5],
                      'X7' : [0]})
prediction2 = Logreg.predict(check)
print('Hasil Pred :', prediction2)

Hasil Pred : [1]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


Jika dibandingkan dengan menggunakan Logistic Regression data yang diberikan dengan nama check2 juga menunjukkan hasil yang sama dengan menggunakan Random Forest.